Repository AY2122S2-CS2113T-T09-4/tp, pull requests merged in 2022-03, with the labels that each got.

#11 Add base classes
  src/main/java/seedu/duke/Commands.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Goods.java
  src/main/java/seedu/duke/Regex.java
  src/main/java/seedu/duke/UserInterface.java
  src/test/java/seedu/duke/CommandsTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: Story

#30 Update developer guide with Good class and list feature
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/Good.puml
  docs/diagrams/List.puml
Labels: documentation

#31 Updated the DG draft thing
  META-INF/MANIFEST.MF
  docs/DeveloperGuide.md
  docs/diagrams/CommandsClass.puml
  docs/diagrams/viewGood.puml
Labels: documentation

#35 Include storage capacity feature and update list feature DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/List.puml
  src/main/java/seedu/duke/Commands.java
  src/main/java/seedu/duke/UserInterface.java
  src/main/java/seedu/duke/Warehouse.java
  src/test/java/seedu/duke/RegexTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: documentation, Story
